root: ./docs/

structure:
  readme: welcome.md
  summary: README.md

redirects:
  installation: getting-started/installation.md
  quick-start: getting-started/quickstart.md
  basics/installation: getting-started/installation.md
  stack-graph: overview/stack-graph.md
  troubleshooting: misc/troubleshooting.md
  examples/demo-project: example-projects/demo-project.md
  examples/tls-project: example-projects/tls-project.md
  examples/using-garden-in-ci: guides/using-garden-in-ci.md
  guides/code-synchronization-dev-mode: guides/code-synchronization.md
  guides/terraform: terraform-plugin/about.md
  providers/conftest-container: reference/providers/conftest-container.md
  providers/conftest-kubernetes: reference/providers/conftest-kubernetes.md
  providers/conftest: reference/providers/conftest.md
  providers/hadolint: reference/providers/hadolint.md♡
  providers/kubernetes: reference/providers/kubernetes.md
  providers/local-kubernetes: reference/providers/local-kubernetes.md
  providers/maven-container: reference/providers/maven-container.md
  providers/openfaas: reference/providers/openfaas.md
  providers/terraform: reference/providers/terraform.md
  module-types/conftest: reference/module-types/conftest.md
  module-types/container: reference/module-types/container.md
  module-types/exec: reference/module-types/exec.md
  module-types/hadolint: reference/module-types/hadolint.md
  module-types/helm: reference/module-types/helm.md
  module-types/kubernetes: reference/module-types/kubernetes.md
  module-types/maven-container: reference/module-types/maven-container.md
  module-types/openfaas: reference/module-types/openfaas.md
  module-types/persistentvolumeclaim: reference/module-types/persistentvolumeclaim.md
  module-types/terraform: reference/module-types/terraform.md
  reference/module-template-config: reference/config-template-config.md
  using-garden/module-templates: using-garden/config-templates.md
  # Redirects after docs restructure (https://github.com/garden-io/garden/pull/3467)
  advanced/terraform: terraform-plugin/about.md
  advanced/pulumi: pulumi-plugin/about.md
  advanced/rbac-config: k8s-plugins/advanced/rbac-config.md
  getting-started: tutorials/your-first-project.md
  getting-started/0-introduction: overview/quickstart
  getting-started/1-installation: getting-started/installation.md
  getting-started/2-connect-to-a-cluster: tutorials/your-first-project/2-connect-to-a-cluster.md
  basics/5-min-quickstart: getting-started/quickstart.md
  other-plugins/container: other-plugins/container
  guides/remote-kubernetes: k8s-plugins/about.md
  guides/in-cluster-building: k8s-plugins/advanced/in-cluster-building.md
  guides/using-helm-charts: k8s-plugins/module-types/helm.md
  guides/using-remote-sources: k8s-plugins/advanced/using-remote-sources.md
  # Redirects set after 2023–09–22
  tutorials/migrating-to-bonsai: guides/migrating-to-bonsai.md
  guides/using-garden-in-ci: use-cases/portable-ci-pipelines.md
  overview/use-cases: use-cases/portable-pipelines.md
